openapi: 3.0.0
info:
  title: Github API
  description: API for fetching results from the Github API
  version: 1.0.0
servers:
  - url: "http://localhost:8080/github-codechallenge/api/github"
paths:
  /repositories:
    post:
      tags:
        - Controller for fetching results from the Github API
      summary: Get user's Repositories which are not forks and correspondent branches
      operationId: getUserRepositories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              description: Github's username/owner name
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GithubRepoResponse'
        '404':
          description: Not Found
        '406':
          description: Not Acceptable
components:
  schemas:
    GithubRepoResponse:
      type: object
      properties:
        repositoryName:
          type: string
          description: Name of the repository
        ownerLogin:
          type: string
          description: Login of the repository owner
        branches:
          type: array
          items:
            $ref: '#/components/schemas/Branch'
    Branch:
      type: object
      properties:
        branchName:
          type: string
          description: Name of the branch
        lastCommitSha:
          type: string
          description: SHA of the last commit on the branch