#spring.application.name=CodeChallenge
#springdoc.swagger-ui.enabled=
server:
  servlet.context-path: /github-codechallenge
  http2.enabled: true
  port: 8080
spring:
  application:
    name: github-codechallenge

git.hub.access-token: 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


springdoc:
  api-docs:
    groups:
      enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html