server:
  servlet.context-path: /github-codechallenge
  http2.enabled: true
  port: 8080
  error:
    include-message: always
spring:
  application:
    name: github-codechallenge

#git.hub.access-token:


springdoc:
  api-docs:
    groups:
      enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html